# version format
version: 0.1.{build}-{branch}

image:
  - Visual Studio 2017

skip_tags: false

skip_commits:
  message: /.*\[ci skip\]/       # Regex for matching commit message

# clone directory
clone_folder: c:\projects\BackToWork

clone_depth: 3                      # clone entire repository history if not defined

build_script:
  - cmd: 'cd src\BackToWork'
  - msbuild BackToWork.sln /verbosity:normal /p:Platform="x86" /p:Configuration=Debug

after_build:
  - cmd: 'echo %cd%'
  - 7z a BackToWork-latest.zip Debug\BackToWork.exe btw.config
  - appveyor PushArtifact BackToWork-latest.zip
